### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by chase-moskal** [chase-moskal/sheep-cart#1]
- [x] loading spinner graphic (render_op) @zenkyuv 
- [x] load cart contents, and sync between tabs @chase-moskal 
- [x] click-to-enlarge images @zenkyuv 
- [x] top-level nav -- (collections) (all products) @chase-moskal 
- [x] use an icon for X button in cart @zenkyuv 
- [x] restyle the demo website to be "sheep-cart" themed, delete "dev-bakery" theming @chase-moskal 
- [x] cart button number badge @chase-moskal 
- [x] mechanism for cart to follow scroll @chase-moskal 
- [x] cart subtotal and fineprint details @chase-moskal 
- [x] sales like "15% off" and showing comparePrice etc @chase-moskal 
- [x] rework devbakery products, collections based on cuisines, "indian", "american", "japanese", etc @chase-moskal
- [x] browser compat @chase-moskal 
- [x] fix cart layout for tiny screens
- [x] fix zero-quantity checkout error
- [x] fix cart loading product-not-found errors, and other errors involving malformed json
- [x] find some way to maintain scroll position when going back to product listing @chase-moskal 
- [x] deploy demo site
- [x] change "choose from x variants" to simply "options"
- [x] control over collections listing, `prioritized-collections` and `hidden-collections`
- [ ] change all dependency targets to es2019, use ponyfills for things like array.at
- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [ ] #9
- [ ] urls to specific variants
- [ ] when doing a search for tags, highlight the searched tags on each product card
- [x] #8
- [x] #10
- [ ] write readme
- [x] #11
- [ ] #12
- [ ] add special rendering for "new" tag, so a special tag appears at the top-right corner of a product card

important
- [x] fix and improve sold out items
  - display sold-out items in the product list (so users notice they are sold out)
  - when loading the cart, remove items that are sold out (big muffin)
  - show "sold out" for variants that are sold out (large fish pakoras)
